In [ ]:
import os
import pandas as pd
from pathlib import Path
from datetime import datetime

In [3]:
cwd = os.getcwd()
data_dir = Path(cwd).parent / 'data'
gym_sets_path = data_dir / 'fetched' / 'gym_sets.csv'

gym_sets = pd.read_csv(gym_sets_path)
gym_sets.head()

,body_weight,cardio,category,created,distance,duration,hidden,id,image,incline,name,notes,plan_id,reps,rest_ms,unit,weight
0,88.9,0,Shoulders,1755675556,0.0,0.0,1,1,NaN,NaN,Arnold press,NaN,NaN,0.0,NaN,kg,0.0
1,88.9,0,Back,1755675556,0.0,0.0,1,2,NaN,NaN,Back extension,NaN,NaN,0.0,NaN,kg,0.0
2,88.9,0,Chest,1755675556,0.0,0.0,1,3,NaN,NaN,Barbell bench press,NaN,NaN,0.0,NaN,kg,0.0
3,88.9,0,Arms,1755675556,0.0,0.0,1,4,NaN,NaN,Barbell biceps curl,NaN,NaN,0.0,NaN,kg,0.0
4,88.9,0,Back,1755675556,0.0,0.0,1,5,NaN,NaN,Barbell bent-over row,NaN,NaN,0.0,NaN,kg,0.0

In [6]:
gym_sets['datetime'] = gym_sets['created'].apply(lambda x: datetime.fromtimestamp(x))
gym_sets['date'] = gym_sets['datetime'].dt.date

gym_sets.head()

,body_weight,cardio,category,created,distance,duration,hidden,id,image,incline,name,notes,plan_id,reps,rest_ms,unit,weight,datetime,date
0,88.9,0,Shoulders,1755675556,0.0,0.0,1,1,NaN,NaN,Arnold press,NaN,NaN,0.0,NaN,kg,0.0,2025-08-20 13:09:16,2025-08-20
1,88.9,0,Back,1755675556,0.0,0.0,1,2,NaN,NaN,Back extension,NaN,NaN,0.0,NaN,kg,0.0,2025-08-20 13:09:16,2025-08-20
2,88.9,0,Chest,1755675556,0.0,0.0,1,3,NaN,NaN,Barbell bench press,NaN,NaN,0.0,NaN,kg,0.0,2025-08-20 13:09:16,2025-08-20
3,88.9,0,Arms,1755675556,0.0,0.0,1,4,NaN,NaN,Barbell biceps curl,NaN,NaN,0.0,NaN,kg,0.0,2025-08-20 13:09:16,2025-08-20
4,88.9,0,Back,1755675556,0.0,0.0,1,5,NaN,NaN,Barbell bent-over row,NaN,NaN,0.0,NaN,kg,0.0,2025-08-20 13:09:16,2025-08-20

In [7]:
from dotenv import load_dotenv
load_dotenv()

GYM_START_DATE = os.getenv('GYM_START_DATE')
GYM_START_DATE

'2025-08-28'

In [19]:
GYM_START_DATE = datetime.strptime(GYM_START_DATE, '%Y-%m-%d').date()
GYM_START_DATE

datetime.date(2025, 8, 28)

In [22]:
gym_sets[gym_sets['date'] > GYM_START_DATE]

,body_weight,cardio,category,created,distance,duration,hidden,id,image,incline,name,notes,plan_id,reps,rest_ms,unit,weight,datetime,date
136,0.0,0,NaN,1756423654,0.0,0.0,1,139,NaN,NaN,Incline dumbbell press,NaN,NaN,0.0,NaN,kg,0.0,2025-08-29 04:57:34,2025-08-29
137,0.0,0,NaN,1756423731,0.0,0.0,1,140,NaN,NaN,Face pull,NaN,NaN,0.0,NaN,kg,0.0,2025-08-29 04:58:51,2025-08-29
138,0.0,0,NaN,1756423889,0.0,0.0,1,161,NaN,NaN,Seal row,NaN,NaN,0.0,NaN,kg,0.0,2025-08-29 05:01:29,2025-08-29
139,0.0,0,NaN,1756423925,0.0,0.0,1,162,NaN,NaN,EZ-bar biceps curl,NaN,NaN,0.0,NaN,kg,0.0,2025-08-29 05:02:05,2025-08-29
140,0.0,0,NaN,1756424190,0.0,0.0,1,218,NaN,NaN,Cable crossover,NaN,NaN,0.0,NaN,kg,0.0,2025-08-29 05:06:30,2025-08-29
141,0.0,0,NaN,1756424401,0.0,0.0,1,241,NaN,NaN,Single-arm dumbbell row,NaN,NaN,0.0,NaN,kg,0.0,2025-08-29 05:10:01,2025-08-29
142,0.0,0,NaN,1756424451,0.0,0.0,1,242,NaN,NaN,Cable pull-over,NaN,NaN,0.0,NaN,kg,0.0,2025-08-29 05:10:51,2025-08-29
143,0.0,0,NaN,1756424466,0.0,0.0,1,243,NaN,NaN,Hammer curl,NaN,NaN,0.0,NaN,kg,0.0,2025-08-29 05:11:06,2025-08-29